-- 개인 사이드 프로젝트 3종 추가: 연어 · Autoblog · JLPT RPG
-- 대상: noino0819 포트폴리오(00000000-0000-0000-0000-000000000001), 전체 7개 언어
-- 기존 projects jsonb 배열 뒤에 append (||)

-- Korean
update public.portfolio_box_portfolio_data
set projects = projects || '[
{"title":"연어 (광역버스 탑승 예측 앱)","period":"2026.07 - 현재","affiliation":"개인 프로젝트","description":"만석이면, 거슬러 오르세요 — 지금 오는 광역버스의 실시간 잔여좌석과 탑승 확률을 예측해, 어느 정류장으로 거슬러 올라가야 앉아갈 수 있는지 알려주는 PWA.","highlights":["경기버스정보 API 연동 — 실시간 잔여좌석·버스 위치·도착 정보 조회","정류장별 탑승 확률 예측 — 좌석 소진 패턴 기반 기대 잔여좌석 계산","상류 정류장 추천 — 도보 시간 포함 총 통근 시간 비교로 최적 탑승 지점 제시","Leaflet 지도 시각화 및 PWA 홈 화면 설치 지원"],"techs":["Next.js","TypeScript","Leaflet","PWA"],"url":"https://yeoneo.vercel.app"},
{"title":"Autoblog (네이버 블로그 자동 포스팅)","period":"2026.06 - 현재","affiliation":"개인 프로젝트","description":"사진과 가게·상품 정보만 넣으면, 스펙 나열이 아닌 경험 중심의 네이버 블로그 글을 자동으로 작성하고 발행까지 해주는 데스크톱 프로그램.","highlights":["LLM 초안 생성 (Claude·GPT·Gemini·NVIDIA) — 강조·구분선·스티커·사진 배치 마커까지 자동 삽입","Playwright 기반 네이버 Smart Editor 자동화 — 임시저장·발행까지 무인 처리","FLUX.1 비전 모델 기반 AI 손그림 썸네일 생성","어투 프리셋 4종 + 시드 기반 스타일 변주로 매번 다른 글 생성","SEO 제목 로테이션 및 필수 키워드 자연 배치"],"techs":["Python","Playwright","LLM","FLUX.1"],"github":"https://github.com/noino0819/blogging"},
{"title":"JLPT RPG (일본어 단어 학습 게임)","period":"2026.05 - 현재","affiliation":"개인 프로젝트","description":"JLPT N5~N1 공식 어휘 4,953단어를 던전을 정복하며 외우는 픽셀 RPG 웹앱. 전 단어에 한자 어원 풀이와 실전 예문 2개 제공.","highlights":["N5~N1 던전 5종 — 어휘·문법·유의 표현 4,953단어 + 예문 9,906개","기억 상태 기반 SRS 복습 — 처음/헷갈림/외움 분류로 자동 복습 큐 구성","Supabase Auth + 네이버 OAuth 로그인, 진행상태 서버 동기화 및 로컬 fallback","엑셀 업로드로 나만의 단어장(MyDeck) 생성","직업·등급 시스템과 픽셀 도트 아트, PWA 설치 지원"],"techs":["React","TypeScript","Supabase","Vercel","PWA"],"url":"https://jlpt-rpg.vercel.app"}
]'::jsonb
where portfolio_id = '00000000-0000-0000-0000-000000000001' and lang = 'ko';

-- English
update public.portfolio_box_portfolio_data
set projects = projects || '[
{"title":"Yeoneo (Bus Boarding Predictor)","period":"2026.07 - Present","affiliation":"Personal Project","description":"''If the bus is full, swim upstream'' — a PWA that predicts real-time remaining seats and boarding probability for commuter buses, telling you which upstream stop to walk to for a seat.","highlights":["Gyeonggi Bus API integration — real-time remaining seats, bus location and arrivals","Per-stop boarding probability — expected seats based on seat-depletion patterns","Upstream stop recommendation — total commute comparison including walking time","Leaflet map visualization, installable PWA"],"techs":["Next.js","TypeScript","Leaflet","PWA"],"url":"https://yeoneo.vercel.app"},
{"title":"Autoblog (Naver Blog Auto-Posting)","period":"2026.06 - Present","affiliation":"Personal Project","description":"A desktop program that turns photos and store/product info into experience-driven Naver blog posts — written, formatted and published automatically.","highlights":["LLM drafting (Claude·GPT·Gemini·NVIDIA) — auto-inserts emphasis, dividers, stickers and photo-placement markers","Playwright automation of Naver Smart Editor — unattended save & publish","AI hand-drawn thumbnails via FLUX.1 vision pipeline","4 tone presets + seed-based style variation for unique posts every time","SEO title rotation and natural keyword placement"],"techs":["Python","Playwright","LLM","FLUX.1"],"github":"https://github.com/noino0819/blogging"},
{"title":"JLPT RPG (Japanese Vocab Game)","period":"2026.05 - Present","affiliation":"Personal Project","description":"A pixel-art RPG web app for conquering all 4,953 official JLPT N5–N1 words, each with kanji etymology and two real-world example sentences.","highlights":["5 dungeons (N5–N1) — 4,953 words + 9,906 example sentences","SRS-style review — new/fuzzy/memorized states build an automatic review queue","Supabase Auth + Naver OAuth, server sync with local-storage fallback","Custom decks (MyDeck) via Excel upload","Class & rank system, handmade pixel art, installable PWA"],"techs":["React","TypeScript","Supabase","Vercel","PWA"],"url":"https://jlpt-rpg.vercel.app"}
]'::jsonb
where portfolio_id = '00000000-0000-0000-0000-000000000001' and lang = 'en';

-- Japanese
update public.portfolio_box_portfolio_data
set projects = projects || '[
{"title":"ヨノ (広域バス乗車予測アプリ)","period":"2026.07 - 現在","affiliation":"個人プロジェクト","description":"「満席なら、上流へ遡ろう」— 広域バスのリアルタイム残席と乗車確率を予測し、どの停留所まで遡れば座れるかを教えてくれるPWA。","highlights":["京畿バス情報API連携 — リアルタイム残席・バス位置・到着情報","停留所別乗車確率予測 — 座席消化パターンに基づく期待残席計算","上流停留所のレコメンド — 徒歩時間込みの総通勤時間比較","Leaflet地図表示・PWAホーム画面インストール対応"],"techs":["Next.js","TypeScript","Leaflet","PWA"],"url":"https://yeoneo.vercel.app"},
{"title":"Autoblog (NAVERブログ自動投稿)","period":"2026.06 - 現在","affiliation":"個人プロジェクト","description":"写真と店舗・商品情報を入れるだけで、体験中心のNAVERブログ記事を自動執筆し、投稿まで行うデスクトッププログラム。","highlights":["LLM下書き生成 (Claude·GPT·Gemini·NVIDIA) — 強調・区切り線・スタンプ・写真配置マーカーを自動挿入","PlaywrightによるSmart Editor自動化 — 下書き保存・公開まで無人処理","FLUX.1ビジョンモデルによるAI手描き風サムネイル生成","口調プリセット4種 + シードベースのスタイル変化","SEOタイトルローテーションとキーワード自然配置"],"techs":["Python","Playwright","LLM","FLUX.1"],"github":"https://github.com/noino0819/blogging"},
{"title":"JLPT RPG (日本語単語学習ゲーム)","period":"2026.05 - 現在","affiliation":"個人プロジェクト","description":"JLPT N5〜N1公式語彙4,953語をダンジョン攻略しながら覚えるピクセルRPGウェブアプリ。全単語に漢字語源解説と実践例文2つを収録。","highlights":["N5〜N1ダンジョン5種 — 語彙・文法・類義表現4,953語 + 例文9,906個","記憶状態ベースのSRS復習 — 自動復習キュー構成","Supabase Auth + NAVER OAuth、サーバー同期とローカルfallback","Excelアップロードで自分だけの単語帳(MyDeck)作成","職業・ランクシステムとピクセルアート、PWA対応"],"techs":["React","TypeScript","Supabase","Vercel","PWA"],"url":"https://jlpt-rpg.vercel.app"}
]'::jsonb
where portfolio_id = '00000000-0000-0000-0000-000000000001' and lang = 'ja';

-- Chinese
update public.portfolio_box_portfolio_data
set projects = projects || '[
{"title":"Yeoneo (广域巴士乘车预测应用)","period":"2026.07 - 现在","affiliation":"个人项目","description":"「满座就逆流而上」 — 预测广域巴士的实时余座和乘车概率，告诉你走到哪个上游站点才能坐着通勤的PWA。","highlights":["京畿巴士信息API对接 — 实时余座·巴士位置·到站信息","按站点预测乘车概率 — 基于座位消耗模式计算期望余座","上游站点推荐 — 含步行时间的总通勤时间比较","Leaflet地图可视化，支持PWA安装"],"techs":["Next.js","TypeScript","Leaflet","PWA"],"url":"https://yeoneo.vercel.app"},
{"title":"Autoblog (NAVER博客自动发布)","period":"2026.06 - 现在","affiliation":"个人项目","description":"只需放入照片和店铺·商品信息，即可自动撰写以体验为中心的NAVER博客文章并完成发布的桌面程序。","highlights":["LLM草稿生成 (Claude·GPT·Gemini·NVIDIA) — 自动插入强调·分隔线·贴纸·照片排版标记","基于Playwright的Smart Editor自动化 — 无人值守保存·发布","FLUX.1视觉模型生成AI手绘风缩略图","4种语气预设 + 基于种子的风格变化","SEO标题轮换与关键词自然布局"],"techs":["Python","Playwright","LLM","FLUX.1"],"github":"https://github.com/noino0819/blogging"},
{"title":"JLPT RPG (日语单词学习游戏)","period":"2026.05 - 现在","affiliation":"个人项目","description":"通过攻略地下城背诵JLPT N5~N1官方词汇4,953个单词的像素RPG网页应用。所有单词均附汉字字源解析和2个实战例句。","highlights":["N5~N1地下城5座 — 词汇·语法·近义表达4,953词 + 例句9,906个","基于记忆状态的SRS复习 — 自动构建复习队列","Supabase Auth + NAVER OAuth登录，服务器同步与本地fallback","Excel上传创建自己的单词本(MyDeck)","职业·等级系统与像素艺术，支持PWA安装"],"techs":["React","TypeScript","Supabase","Vercel","PWA"],"url":"https://jlpt-rpg.vercel.app"}
]'::jsonb
where portfolio_id = '00000000-0000-0000-0000-000000000001' and lang = 'zh';

-- German
update public.portfolio_box_portfolio_data
set projects = projects || '[
{"title":"Yeoneo (Bus-Sitzplatz-Vorhersage)","period":"2026.07 - Gegenwart","affiliation":"Persönliches Projekt","description":"''Wenn der Bus voll ist, schwimm stromaufwärts'' — eine PWA, die Restplätze und Einstiegswahrscheinlichkeit von Pendlerbussen in Echtzeit vorhersagt und die beste Haltestelle empfiehlt.","highlights":["Gyeonggi-Bus-API — Restplätze, Busposition und Ankünfte in Echtzeit","Einstiegswahrscheinlichkeit pro Haltestelle auf Basis von Sitzplatzmustern","Empfehlung stromaufwärts gelegener Haltestellen inkl. Fußweg-Vergleich","Leaflet-Karte, installierbare PWA"],"techs":["Next.js","TypeScript","Leaflet","PWA"],"url":"https://yeoneo.vercel.app"},
{"title":"Autoblog (Naver-Blog-Automatisierung)","period":"2026.06 - Gegenwart","affiliation":"Persönliches Projekt","description":"Ein Desktop-Programm, das aus Fotos und Laden-/Produktinfos erlebniszentrierte Naver-Blogartikel automatisch schreibt, formatiert und veröffentlicht.","highlights":["LLM-Entwürfe (Claude·GPT·Gemini·NVIDIA) mit automatischen Format-Markern","Playwright-Automatisierung des Naver Smart Editors — Speichern & Veröffentlichen ohne Aufsicht","KI-Thumbnails im Handzeichnungsstil via FLUX.1","4 Tonalitäts-Presets + seedbasierte Stilvariation","SEO-Titelrotation und natürliche Keyword-Platzierung"],"techs":["Python","Playwright","LLM","FLUX.1"],"github":"https://github.com/noino0819/blogging"},
{"title":"JLPT RPG (Japanisch-Vokabelspiel)","period":"2026.05 - Gegenwart","affiliation":"Persönliches Projekt","description":"Eine Pixel-RPG-Web-App, mit der man alle 4.953 offiziellen JLPT-Vokabeln (N5–N1) durch Dungeon-Eroberung lernt — mit Kanji-Etymologie und je zwei Beispielsätzen.","highlights":["5 Dungeons (N5–N1) — 4.953 Wörter + 9.906 Beispielsätze","SRS-Wiederholung nach Erinnerungsstatus mit automatischer Warteschlange","Supabase Auth + Naver OAuth, Server-Sync mit lokalem Fallback","Eigene Decks (MyDeck) per Excel-Upload","Klassen- & Rangsystem, handgemachte Pixel-Art, installierbare PWA"],"techs":["React","TypeScript","Supabase","Vercel","PWA"],"url":"https://jlpt-rpg.vercel.app"}
]'::jsonb
where portfolio_id = '00000000-0000-0000-0000-000000000001' and lang = 'de';

-- French
update public.portfolio_box_portfolio_data
set projects = projects || '[
{"title":"Yeoneo (Prédiction de places de bus)","period":"2026.07 - Présent","affiliation":"Projet personnel","description":"''Si le bus est plein, remontez le courant'' — une PWA qui prédit en temps réel les places restantes et la probabilité de monter, et recommande le meilleur arrêt en amont.","highlights":["API des bus de Gyeonggi — places restantes, position et arrivées en temps réel","Probabilité de montée par arrêt selon les schémas d''occupation des sièges","Recommandation d''arrêts en amont avec comparaison du trajet total à pied inclus","Carte Leaflet, PWA installable"],"techs":["Next.js","TypeScript","Leaflet","PWA"],"url":"https://yeoneo.vercel.app"},
{"title":"Autoblog (Publication auto sur Naver Blog)","period":"2026.06 - Présent","affiliation":"Projet personnel","description":"Un programme de bureau qui transforme photos et infos boutique/produit en articles de blog Naver centrés sur l''expérience — rédigés, mis en forme et publiés automatiquement.","highlights":["Rédaction par LLM (Claude·GPT·Gemini·NVIDIA) avec marqueurs de mise en forme automatiques","Automatisation du Smart Editor Naver via Playwright — enregistrement et publication sans surveillance","Miniatures IA façon dessin à la main via FLUX.1","4 préréglages de ton + variation de style par seed","Rotation de titres SEO et placement naturel des mots-clés"],"techs":["Python","Playwright","LLM","FLUX.1"],"github":"https://github.com/noino0819/blogging"},
{"title":"JLPT RPG (Jeu de vocabulaire japonais)","period":"2026.05 - Présent","affiliation":"Projet personnel","description":"Une web app RPG en pixel art pour conquérir les 4 953 mots officiels du JLPT N5–N1, chacun avec étymologie des kanjis et deux phrases d''exemple.","highlights":["5 donjons (N5–N1) — 4 953 mots + 9 906 phrases d''exemple","Révision type SRS selon l''état de mémorisation, file de révision automatique","Supabase Auth + OAuth Naver, synchronisation serveur avec repli local","Decks personnalisés (MyDeck) par import Excel","Système de classes et de rangs, pixel art fait main, PWA installable"],"techs":["React","TypeScript","Supabase","Vercel","PWA"],"url":"https://jlpt-rpg.vercel.app"}
]'::jsonb
where portfolio_id = '00000000-0000-0000-0000-000000000001' and lang = 'fr';

-- Spanish
update public.portfolio_box_portfolio_data
set projects = projects || '[
{"title":"Yeoneo (Predicción de asientos de bus)","period":"2026.07 - Presente","affiliation":"Proyecto personal","description":"''Si el bus va lleno, nada contra la corriente'' — una PWA que predice en tiempo real los asientos libres y la probabilidad de subir, recomendando la mejor parada río arriba.","highlights":["API de buses de Gyeonggi — asientos libres, posición y llegadas en tiempo real","Probabilidad de abordaje por parada según patrones de ocupación","Recomendación de paradas río arriba comparando el trayecto total con caminata incluida","Mapa Leaflet, PWA instalable"],"techs":["Next.js","TypeScript","Leaflet","PWA"],"url":"https://yeoneo.vercel.app"},
{"title":"Autoblog (Publicación automática en Naver Blog)","period":"2026.06 - Presente","affiliation":"Proyecto personal","description":"Un programa de escritorio que convierte fotos e información de tiendas/productos en artículos de Naver Blog centrados en la experiencia — redactados, formateados y publicados automáticamente.","highlights":["Borradores con LLM (Claude·GPT·Gemini·NVIDIA) con marcadores de formato automáticos","Automatización del Smart Editor de Naver con Playwright — guardado y publicación sin supervisión","Miniaturas IA estilo dibujo a mano con FLUX.1","4 presets de tono + variación de estilo por semilla","Rotación de títulos SEO y colocación natural de palabras clave"],"techs":["Python","Playwright","LLM","FLUX.1"],"github":"https://github.com/noino0819/blogging"},
{"title":"JLPT RPG (Juego de vocabulario japonés)","period":"2026.05 - Presente","affiliation":"Proyecto personal","description":"Una web app RPG de pixel art para conquistar las 4.953 palabras oficiales del JLPT N5–N1, cada una con etimología de kanji y dos frases de ejemplo.","highlights":["5 mazmorras (N5–N1) — 4.953 palabras + 9.906 frases de ejemplo","Repaso tipo SRS según estado de memorización, cola de repaso automática","Supabase Auth + OAuth de Naver, sincronización con servidor y fallback local","Mazos propios (MyDeck) mediante carga de Excel","Sistema de clases y rangos, pixel art hecho a mano, PWA instalable"],"techs":["React","TypeScript","Supabase","Vercel","PWA"],"url":"https://jlpt-rpg.vercel.app"}
]'::jsonb
where portfolio_id = '00000000-0000-0000-0000-000000000001' and lang = 'es';
